---

# caps
# "rubocop -a" to run caps

Layout/EmptyLinesAroundAttributeAccessor:
    Enabled: false

Layout/LineLength:
    Max: 210

Layout/SpaceAroundMethodCallOperator:
    Enabled: false

Lint/DeprecatedOpenSSLConstant:
    Enabled: true

Lint/MixedRegexpCaptureTypes:
    Enabled: true

Lint/RaiseException:
    Enabled: true

Lint/StructNewOverride:
    Enabled: false

Metrics/AbcSize:
    Max: 60

Metrics/BlockLength:
    Max: 130

Metrics/ClassLength:
    Max: 300

Metrics/MethodLength:
    Max: 30

Metrics/ModuleLength:
    Max: 200

Metrics/ParameterLists:
    Max: 10

Style/ExponentialNotation:
    Enabled: true

Style/FrozenStringLiteralComment:
    Enabled: false

Style/GlobalVars:
    Enabled: false

Style/HashEachMethods:
    Enabled: true

Style/HashTransformKeys:
    Enabled: true

Style/HashTransformValues:
    Enabled: true

Style/RedundantRegexpCharacterClass:
    Enabled: true

Style/RedundantRegexpEscape:
    Enabled: true

Style/SlicingWithRange:
    Enabled: false